
apiVersion: platform.example.com/v1alpha1
kind: AppService
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.name | quote }}
    app.kubernetes.io/managed-by: argocd
spec:
  namespace: {{ .Values.appService.namespace | quote }}
  chartName: {{ .Values.appService.chartName | quote }}
  chartVersion: {{ .Values.appService.chartVersion | quote }}
  port: {{ .Values.appService.port }}
  replicas: {{ .Values.appService.replicas }}
  image:
    repository: {{ .Values.appService.image.repository | quote }}
    tag: {{ .Values.appService.image.tag | quote }}

